const IMAGE_PATH = '/assets/images';

export const appAssets = {
  googleIcon: `${IMAGE_PATH}/google.svg`,
  facebookIcon: `${IMAGE_PATH}/facebook.svg`,
  emptyCartIcon: `${IMAGE_PATH}/no-product.png`,
  emptyOrderIcon: `${IMAGE_PATH}/empty-order.png`,
  payCardIcon: `${IMAGE_PATH}/pay-card.svg`,
  hangerIcon: `${IMAGE_PATH}/hanger-icon.svg`,
  logo: `${IMAGE_PATH}/logo.png`,
  promotion: `${IMAGE_PATH}/promotion.png`,
  promotionBanner: `${IMAGE_PATH}/promotion-banner.png`,
  bigSale50: `${IMAGE_PATH}/big-sale-50.jpg`,
  bigSale60: `${IMAGE_PATH}/big-sale-60.jpg`,
  bigSale70: `${IMAGE_PATH}/big-sale-70.jpg`,
  couponIcon: `${IMAGE_PATH}/coupon.png`,
  storageInstructions: `${IMAGE_PATH}/hdbq.png`,
  noImageAvailable: `${IMAGE_PATH}/no-image-available.jpg`,
  loadingGif: `${IMAGE_PATH}/loading.gif`,
  notFound: `${IMAGE_PATH}/404-not-found.jpg`,
  serverError: `${IMAGE_PATH}/500-server-error.png`,
  banner1: `${IMAGE_PATH}/banner1.jpg`,
  banner2: `${IMAGE_PATH}/banner2.jpg`,
  banner3: `${IMAGE_PATH}/banner3.jpg`,
  banner4: `${IMAGE_PATH}/banner4.jpg`,
  banner5: `${IMAGE_PATH}/banner5.jpg`,
  banner6: `${IMAGE_PATH}/banner6.jpg`,
  banner7: `${IMAGE_PATH}/banner7.jpg`,
  banner8: `${IMAGE_PATH}/banner8.jpg`,
  banner9: `${IMAGE_PATH}/banner9.jpg`,
  banner10: `${IMAGE_PATH}/banner10.jpg`,
  banner11: `${IMAGE_PATH}/banner11.jpg`,
};
