import { ReactElement } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import Intro from '@/common/components/Intro';
import HomeCarousel from '@/modules/home/components/Carousel';
import HomePromotionBanner from '@/modules/home/components/HomePromotionBanner';
import HotProducts from '@/modules/home/components/HotProducts';
import ProductsOfType from '@/modules/home/components/TShirtProducts';
import SaleOffProducts from '@/modules/home/components/SaleOffProducts';
import { getDiscountProducts, getHotProducts, getProductsByType } from '@/services/productRequests';
import { getIntroImages } from '@/services/imageRequests';
import { useRouter } from 'next/router';
import { Stack } from '@mui/material';
import { appAssets } from '@/common/assets';
import config from '../config';
import 'lightgallery.js/dist/css/lightgallery.css';
import 'react-responsive-carousel/lib/styles/carousel.min.css';

export default function Home({
  hotProducts = [],
  discountProducts = [],
  tshirtProducts = [],
  trouserProducts = [],
  introImages = [],
}: InferGetStaticPropsType<typeof getStaticProps>): ReactElement {
  const router = useRouter();

  const navigateToProductsPage = (type: string) => {
    router.push(`${config.routes.products}?type=${type}`);
  };

  return (
    <>
      <Head>
        <title>Brother Shop - Cửa Hàng Online Quần Áo Thời Trang Nam Nữ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="xl:px-[3%]">
        <HomeCarousel />
        <Intro images={introImages} />
        <HomePromotionBanner />
        <HotProducts products={hotProducts} />
        <Stack justifyContent="center">
          <Image src={appAssets.banner3} alt="" width={1000} height={1000} className="w-full" />
        </Stack>
        <ProductsOfType products={tshirtProducts} onSeeMore={navigateToProductsPage} keyword="Áo Thun" />
        <Stack direction={{ md: 'row' }} justifyContent="center" sx={{ mt: 10 }}>
          <Image src={appAssets.banner4} alt="" width={300} height={300} className="w-full" />
          <Image src={appAssets.banner5} alt="" width={300} height={300} className="w-full" />
        </Stack>
        <ProductsOfType products={trouserProducts} onSeeMore={navigateToProductsPage} keyword="Quần" />
        <SaleOffProducts products={discountProducts} />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const promises = [
    getHotProducts(),
    getDiscountProducts(),
    getProductsByType('Áo Thun'),
    getProductsByType('Quần'),
    getIntroImages(),
  ];
  const [hotProducts, discountProducts, tshirtProducts, trouserProducts, introImages] = await Promise.all(promises);

  return {
    props: {
      hotProducts,
      discountProducts,
      tshirtProducts,
      trouserProducts,
      introImages,
    },
  };
};
